// <auto-generated />
using System;
using KeepGrouped.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeepGrouped.Migrations
{
    [DbContext(typeof(KeepGroupedDb))]
    [Migration("20260920143720_AddChannelCategories")]
    partial class AddChannelCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventEventRole", b =>
                {
                    b.Property<string>("EventRolesId")
                        .HasColumnType("text");

                    b.Property<string>("EventsId")
                        .HasColumnType("text");

                    b.HasKey("EventRolesId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("EventEventRole");
                });

            modelBuilder.Entity("EventStorageFile", b =>
                {
                    b.Property<string>("EventsId")
                        .HasColumnType("text");

                    b.Property<string>("FilesKey")
                        .HasColumnType("text");

                    b.HasKey("EventsId", "FilesKey");

                    b.HasIndex("FilesKey");

                    b.ToTable("EventStorageFile");
                });

            modelBuilder.Entity("KeepGrouped.API.Chat.Channel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("KeepGrouped.API.Chat.ChannelAck", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<DateTime>("AckAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelAcks");
                });

            modelBuilder.Entity("KeepGrouped.API.Chat.ChannelCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("ChannelCategories");
                });

            modelBuilder.Entity("KeepGrouped.API.Chat.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<DateTime?>("EditAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageRefId")
                        .HasColumnType("character varying(36)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageRefId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ChannelId", "SentAt")
                        .HasDatabaseName("IX_Messages_ChannelId_SentAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("KeepGrouped.API.Events.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("KeepGrouped.API.Events.EventRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("EventRoles");
                });

            modelBuilder.Entity("KeepGrouped.API.Events.Registration", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("KeepGrouped.API.Roles.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("KeepGrouped.API.Storage.StorageFile", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatorId")
                        .HasColumnType("text");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("CreatorId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("KeepGrouped.API.Users.Invitation.Invitation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Usages")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("KeepGrouped.API.Users.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ExpireAt")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("KeepGrouped.API.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvatarKey")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventEventRole", b =>
                {
                    b.HasOne("KeepGrouped.API.Events.EventRole", null)
                        .WithMany()
                        .HasForeignKey("EventRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeepGrouped.API.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventStorageFile", b =>
                {
                    b.HasOne("KeepGrouped.API.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeepGrouped.API.Storage.StorageFile", null)
                        .WithMany()
                        .HasForeignKey("FilesKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KeepGrouped.API.Chat.Channel", b =>
                {
                    b.HasOne("KeepGrouped.API.Chat.ChannelCategory", null)
                        .WithMany()
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("KeepGrouped.API.Chat.ChannelAck", b =>
                {
                    b.HasOne("KeepGrouped.API.Chat.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeepGrouped.API.Users.User", "User")
                        .WithMany("ChannelsAckMsg")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeepGrouped.API.Chat.Message", b =>
                {
                    b.HasOne("KeepGrouped.API.Chat.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeepGrouped.API.Chat.Message", "MessageRef")
                        .WithMany()
                        .HasForeignKey("MessageRefId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KeepGrouped.API.Users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("MessageRef");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("KeepGrouped.API.Events.Event", b =>
                {
                    b.HasOne("KeepGrouped.API.Chat.Channel", "Channel")
                        .WithOne("Event")
                        .HasForeignKey("KeepGrouped.API.Events.Event", "ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeepGrouped.API.Users.User", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("KeepGrouped.API.Events.Registration", b =>
                {
                    b.HasOne("KeepGrouped.API.Events.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeepGrouped.API.Events.EventRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeepGrouped.API.Users.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeepGrouped.API.Storage.StorageFile", b =>
                {
                    b.HasOne("KeepGrouped.API.Users.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("KeepGrouped.API.Users.User", b =>
                {
                    b.HasOne("KeepGrouped.API.Storage.StorageFile", "Avatar")
                        .WithOne()
                        .HasForeignKey("KeepGrouped.API.Users.User", "AvatarKey");

                    b.HasOne("KeepGrouped.API.Roles.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KeepGrouped.API.Chat.Channel", b =>
                {
                    b.Navigation("Event");
                });

            modelBuilder.Entity("KeepGrouped.API.Events.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("KeepGrouped.API.Roles.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KeepGrouped.API.Users.User", b =>
                {
                    b.Navigation("ChannelsAckMsg");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
